"""Add designations field to candidates table

Revision ID: 46d35f0707f9
Revises: 218b69f6b762
Create Date: 2025-12-09 15:02:04.140192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46d35f0707f9'
down_revision = '218b69f6b762'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('designations', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'designations')
    # ### end Alembic commands ###
